## 3. AIF360 적용

- 특정 feature에 대하여 라벨의 분포가 편향되어있는지를 판단합니다.

- AIF(AIF) 360: 라벨 분포가 편향되어 있으면 안 되는 feature에 대하여 교정을 할 수 있도록 도와주는 라이브러리.

- 불균형 교정 전과 교정 후 metric 변화를 xgboostclassifier라는 모델을 통해 수치화해보겠습니다.

In [ ]:
from sklearn.datasets import fetch_openml

import copy
from pathlib import Path

# data load
path_lecture = Path("data")
adult_data = fetch_openml(name="adult", version=2, as_frame=True)
raw_df = adult_data.frame
raw_df.to_csv(path_lecture / "adult_income.csv", index=False)

display(raw_df.head())
print(f"Data Shape: {raw_df.shape}", end="\n\n")

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,class
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,18,NaN,103497,Some-college,10,Never-married,NaN,Own-child,White,Female,0,0,30,United-States,<=50K

Data Shape: (48842, 15)

PreRequisite for AIF360 

- 결측치 제거

- label encoding이나 ont-hot encoding된 protected attribute

    - protected attribute: 법적으로 차별 받으면 안 되는 특징(legally protect against discrimination)

    - 반드시 categorical feature여야 함.

- protected attribute는 privileged groups vs unprivileged group으로 구분

- 데이터프레임은 반드시 BinaryLabelDataset이나 StandardDataset 중 하나여야 합니다.

In [38]:
from aif360.datasets import BinaryLabelDataset
from sklearn.preprocessing import LabelEncoder
from pprint import pprint

df = copy.deepcopy(raw_df)
df = df.dropna(how="any")

drop_columns = ["education"]
encoding_columns = ["workclass","marital-status","occupation","relationship","race","sex","native-country",'class']

# 반드시 결측치가 제거 되어야 합니다.
df_filtered = df.drop(columns=drop_columns)
display(df_filtered.head(3))

# 라벨 인코딩
encoding_mappings = {}
for col in encoding_columns:
    le = LabelEncoder()
    df_filtered[col] = le.fit_transform(df_filtered[col].astype(str)) 
    encoding_mappings[col] = dict(zip(le.classes_, le.transform(le.classes_)))

pprint(encoding_mappings)

,age,workclass,fnlwgt,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,class
0,25,Private,226802,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,89814,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,336951,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K

{'class': {'<=50K': 0, '>50K': 1},
 'marital-status': {'Divorced': 0,
                    'Married-AF-spouse': 1,
                    'Married-civ-spouse': 2,
                    'Married-spouse-absent': 3,
                    'Never-married': 4,
                    'Separated': 5,
                    'Widowed': 6},
 'native-country': {'Cambodia': 0,
                    'Canada': 1,
                    'China': 2,
                    'Columbia': 3,
                    'Cuba': 4,
                    'Dominican-Republic': 5,
                    'Ecuador': 6,
                    'El-Salvador': 7,
                    'England': 8,
                    'France': 9,
                    'Germany': 10,
                    'Greece': 11,
                    'Guatemala': 12,
                    'Haiti': 13,
                    'Holand-Netherlands': 14,
                    'Honduras': 15,
                    'Hong': 16,
                    'Hungary': 17,
                    'India': 18,
                    'Iran': 19,
                    'Ireland': 20,
                    'Italy': 21,
                    'Jamaica': 22,
                    'Japan': 23,
                    'Laos': 24,
                    'Mexico': 25,
                    'Nicaragua': 26,
                    'Outlying-US(Guam-USVI-etc)': 27,
                    'Peru': 28,
                    'Philippines': 29,
                    'Poland': 30,
                    'Portugal': 31,
                    'Puerto-Rico': 32,
                    'Scotland': 33,
                    'South': 34,
                    'Taiwan': 35,
                    'Thailand': 36,
                    'Trinadad&Tobago': 37,
                    'United-States': 38,
                    'Vietnam': 39,
                    'Yugoslavia': 40},
 'occupation': {'Adm-clerical': 0,
                'Armed-Forces': 1,
                'Craft-repair': 2,
                'Exec-managerial': 3,
                'Farming-fishing': 4,
                'Handlers-cleaners': 5,
                'Machine-op-inspct': 6,
                'Other-service': 7,
                'Priv-house-serv': 8,
                'Prof-specialty': 9,
                'Protective-serv': 10,
                'Sales': 11,
                'Tech-support': 12,
                'Transport-moving': 13},
 'race': {'Amer-Indian-Eskimo': 0,
          'Asian-Pac-Islander': 1,
          'Black': 2,
          'Other': 3,
          'White': 4},
 'relationship': {'Husband': 0,
                  'Not-in-family': 1,
                  'Other-relative': 2,
                  'Own-child': 3,
                  'Unmarried': 4,
                  'Wife': 5},
 'sex': {'Female': 0, 'Male': 1},
 'workclass': {'Federal-gov': 0,
               'Local-gov': 1,
               'Private': 2,
               'Self-emp-inc': 3,
               'Self-emp-not-inc': 4,
               'State-gov': 5,
               'Without-pay': 6}}

In [ ]:
from aif360.datasets import BinaryLabelDataset
from sklearn.preprocessing import LabelEncoder
from pprint import pprint
from sklearn.model_selection import train_test_split

# DataLeakage를 막기 위해서 미리 test 데이터셋을 분류해둡니다.
train, test = train_test_split(df_filtered, test_size=0.2, random_state=42, stratify=df_filtered['class'])

display(train.head(3))
protected_attrs = ['sex']

# 데이터 프레임을 반드시 BinaryLabelDataset이나 StandardDataset 중 하나로 바꿔야 합니다. 
dataset = BinaryLabelDataset(df=train, label_names=['class'], protected_attribute_names=protected_attrs) 
print(dataset.instance_weights)

,age,workclass,fnlwgt,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,class
0,25,Private,226802,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,89814,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,336951,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K

{'class': {'<=50K': 0, '>50K': 1},
 'marital-status': {'Divorced': 0,
                    'Married-AF-spouse': 1,
                    'Married-civ-spouse': 2,
                    'Married-spouse-absent': 3,
                    'Never-married': 4,
                    'Separated': 5,
                    'Widowed': 6},
 'native-country': {'Cambodia': 0,
                    'Canada': 1,
                    'China': 2,
                    'Columbia': 3,
                    'Cuba': 4,
                    'Dominican-Republic': 5,
                    'Ecuador': 6,
                    'El-Salvador': 7,
                    'England': 8,
                    'France': 9,
                    'Germany': 10,
                    'Greece': 11,
                    'Guatemala': 12,
                    'Haiti': 13,
                    'Holand-Netherlands': 14,
                    'Honduras': 15,
                    'Hong': 16,
                    'Hungary': 17,
                    'India': 18,
                    'Iran': 19,
                    'Ireland': 20,
                    'Italy': 21,
                    'Jamaica': 22,
                    'Japan': 23,
                    'Laos': 24,
                    'Mexico': 25,
                    'Nicaragua': 26,
                    'Outlying-US(Guam-USVI-etc)': 27,
                    'Peru': 28,
                    'Philippines': 29,
                    'Poland': 30,
                    'Portugal': 31,
                    'Puerto-Rico': 32,
                    'Scotland': 33,
                    'South': 34,
                    'Taiwan': 35,
                    'Thailand': 36,
                    'Trinadad&Tobago': 37,
                    'United-States': 38,
                    'Vietnam': 39,
                    'Yugoslavia': 40},
 'occupation': {'Adm-clerical': 0,
                'Armed-Forces': 1,
                'Craft-repair': 2,
                'Exec-managerial': 3,
                'Farming-fishing': 4,
                'Handlers-cleaners': 5,
                'Machine-op-inspct': 6,
                'Other-service': 7,
                'Priv-house-serv': 8,
                'Prof-specialty': 9,
                'Protective-serv': 10,
                'Sales': 11,
                'Tech-support': 12,
                'Transport-moving': 13},
 'race': {'Amer-Indian-Eskimo': 0,
          'Asian-Pac-Islander': 1,
          'Black': 2,
          'Other': 3,
          'White': 4},
 'relationship': {'Husband': 0,
                  'Not-in-family': 1,
                  'Other-relative': 2,
                  'Own-child': 3,
                  'Unmarried': 4,
                  'Wife': 5},
 'sex': {'Female': 0, 'Male': 1},
 'workclass': {'Federal-gov': 0,
               'Local-gov': 1,
               'Private': 2,
               'Self-emp-inc': 3,
               'Self-emp-not-inc': 4,
               'State-gov': 5,
               'Without-pay': 6}}

,age,workclass,fnlwgt,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,class
12660,35,4,61343,9,0,6,4,4,1,0,0,40,38,0
24287,19,2,127190,9,4,7,3,4,0,0,0,15,38,0
19245,27,2,193701,9,4,2,3,4,0,0,0,45,38,0

[1. 1. 1. ... 1. 1. 1.]

- SPD (Statistical Parity Difference): It is the difference between the mean probability of favorable outcomes between underprivileged and privileged groups. A negative number is bad, and a positive number is better, yet a number closer to zero is always preferable.


- Disparate Impact (DI): Disparate impact is exactly like Statistical Parity Difference, except it’s the ratio, not the difference. And as ratios go closer to one, the better and under one would mean a disadvantage.

출처: https://medium.com/@ananyamazing/xai-bias-prediction-3497f02c007c

In [49]:
from aif360.metrics import BinaryLabelDatasetMetric

metric = BinaryLabelDatasetMetric(dataset, 
                                privileged_groups=[{'sex': 1}],
                                unprivileged_groups=[{'sex': 0}]
                            )  

print("원본 데이터 편향성 점검")
print("Disparate Impact (DI):", metric.disparate_impact())  
print(f"특권 집단이 {1/metric.disparate_impact() :2f}배 특권을 받고 있다.")
print("Statistical Parity Difference (SPD):", metric.statistical_parity_difference())

원본 데이터 편향성 점검
Disparate Impact (DI): 0.3532397417544619
특권 집단이 2.830939배 특권을 받고 있다.
Statistical Parity Difference (SPD): -0.20304031058036154

In [50]:
from sklearn.metrics import accuracy_score, f1_score, recall_score, precision_score
from xgboost import XGBClassifier

def train_and_evaluate(X_train, y_train, X_test, y_test, sample_weight=None):
    model = XGBClassifier()
    model.fit(X_train, y_train, sample_weight=sample_weight)
    
    y_pred = model.predict(X_test)
    
    metrics = {
        'accuracy': accuracy_score(y_test, y_pred),
        'f1_score': f1_score(y_test, y_pred),
        'recall': recall_score(y_test, y_pred),
        'precision': precision_score(y_test, y_pred)
    }
    
    return metrics
X_train = train.drop(columns=['class'])
X_test = test.drop(columns=['class'])
y_train = train['class']
y_test = test['class']

original_metrics = train_and_evaluate(X_train, y_train, X_test, y_test)
print("불균형 조정 전")
pprint(original_metrics)

불균형 조정 전
{'accuracy': 0.8671088999447208,
 'f1_score': 0.713126491646778,
 'precision': 0.7669404517453798,
 'recall': 0.6663693131132917}

In [51]:
from aif360.algorithms.preprocessing import Reweighing

# Reweighing 적용
reweigher = Reweighing(privileged_groups=[{'sex': 1}], 
                        unprivileged_groups=[{'sex': 0}])

In [44]:
balanced_dataset = reweigher.fit_transform(dataset)

# 균형 조정 후 데이터 변환
df_balanced = balanced_dataset.convert_to_dataframe()[0]
print(set(balanced_dataset.instance_weights))

{0.8459768287619984, 1.0963426897271873, 2.234897875982477, 0.7894547485596456}

In [45]:
processed_metrics = train_and_evaluate(X_train, y_train, X_test, y_test, sample_weight=balanced_dataset.instance_weights)
print("불균형 조정 후")
pprint(processed_metrics)

불균형 조정 후
{'accuracy': 0.8647871752349364,
 'f1_score': 0.6982482112015791,
 'precision': 0.7813362782992822,
 'recall': 0.6311329170383586}

In [48]:
import pandas as pd

display(pd.DataFrame([original_metrics, processed_metrics], index = ["before","after"]))

        accuracy  f1_score    recall  precision
before  0.867109  0.713126  0.666369   0.766940
after   0.864787  0.698248  0.631133   0.781336